version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: chatDB
      POSTGRES_USER: mihalishcher
      POSTGRES_DB: chatDB
    ports:
      - "5432:5432"